version: '3'

services:
  web:
    container_name: handover
    image: vatsca/apache:php-8.1
    ports:
        - 5000:80
        - 5001:443
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
      - ./apache:/var/www/logs