---
name: "Build"

on:
  push:
    paths-ignore:
      - "**.md"

env:
  IMAGE_NAME: vatsim-scandinavia/handover
  TARGET_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-container:
    name: Build Stands Container
    runs-on: ubuntu-latest
    steps:
      - name: configure docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=sha,event=branch,prefix=
            type=semver,event=tag,pattern=v{{version}}
            type=semver,event=tag,pattern=v{{major}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: build & push container image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}